version: "3"
services:
    app:
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        container_name: nginx-proxy
        networks:
            - proxy-net
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - ./_hsts.conf:/app/templates/_hsts.conf:ro

networks:
    proxy-net:
        name: proxy-network
        driver: bridge
