# QBittorrent
# Web UI: http://qbittorent:8085

services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorent
        networks:
            - proxy-net
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - WEBUI_PORT=8085
        volumes:
            - ./config:/config
            - ./downloads:/downloads
        ports:
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped

networks:
    proxy-net:
        name: proxy-network
        external: true
