# Jellyseerr
# Web UI: http://jellyseerr:5055

services:
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Paris
        networks:
            - proxy-net
        volumes:
            - ./config:/app/config
        restart: always
        labels:
            traefik.enable: true
            traefik.http.routers.jellyseerr.entrypoints: web,websecure
            traefik.http.routers.jellyseerr.tls: true
            traefik.http.routers.jellyseerr.tls.certresolver: production
            traefik.http.routers.jellyseerr.rule: Host(`mediar.example.com`)
            traefik.http.services.jellyseerr.loadbalancer.server.port: 5055

networks:
    proxy-net:
        name: proxy-network
        external: true