# Jellyseerr
# Web UI: http://jellyseerr:5055

services:
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Paris
        networks:
            - proxy-net
        volumes:
            - ./config:/app/config
        restart: always

networks:
    proxy-net:
        name: proxy-network
        external: true
