# Umami
# Web UI: http://umami:3000

services:
    umami:
        image: ghcr.io/umami-software/umami:postgresql-v2.11.3
        container_name: umami
        restart: unless-stopped
        environment:
            # url format :
            # DATABASE_URL: postgresql://username:password@hostname:port/database
            DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
            DATABASE_TYPE: postgresql
        env_file:
            - .env
        networks:
            - umami-net
            - proxy-net

    db:
        image: postgres:15-alpine
        container_name: umami-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: umami
            POSTGRES_USER: umami
            POSTGRES_PASSWORD: umami
        volumes:
            - umami-db-data:/var/lib/postgresql/data
        networks:
            - umami-net

networks:
    umami-net:
    proxy-net:
        name: proxy-network
        external: true

volumes:
    umami-db-data:
