# Filebrowser
# Web UI: http://filebrowser:80
# Default username/password is admin/admin
# Create filebrowser.db before starting the container

services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        networks:
            - proxy-net
        volumes:
            # all monted volumes must be mount to /srv
            - ./data/user:/srv/user
            - ./db/filebrowser.db:/database.db
        restart: always
        labels:
            traefik.enable: true
            traefik.http.routers.filebrowser.entrypoints: web,websecure
            traefik.http.routers.filebrowser.tls: true
            traefik.http.routers.filebrowser.tls.certresolver: production
            traefik.http.routers.filebrowser.rule: Host(`file.example.com`)
            traefik.http.services.filebrowser.loadbalancer.server.port: 80

networks:
    proxy-net:
        name: proxy-network
        external: true
