# NTFY
# Web UI: http://ntfy:80

services:
    ntfy:
        image: binwiederhier/ntfy
        container_name: ntfy
        command:
            - serve
        environment:
            TZ: Europe/Paris
        volumes:
            - ./data/cache:/var/cache/ntfy
            - ./data/db/:/var/lib/ntfy/
            - ./config/server.yml:/etc/ntfy/server.yml
        healthcheck: # optional: remember to adapt the host:port to your environment
            test: [ "CMD-SHELL", "wget -q --tries=1 http://ntfy:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1" ]
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: always
        networks:
            - proxy-net
        labels:
            traefik.enable: true
            traefik.http.routers.ntfy.entrypoints: web,websecure
            traefik.http.routers.ntfy.tls: true
            traefik.http.routers.ntfy.tls.certresolver: production
            traefik.http.routers.ntfy.rule: Host(`ntfy.example.com`)
            traefik.http.services.ntfy.loadbalancer.server.port: 80

networks:
    proxy-net:
        external: true
        name: proxy-network