################################################################
# Global configuration
################################################################
global:
    checkNewVersion: true
    sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################
entryPoints:
    web:
        address: :80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
    websecure:
        address: :443
    metrics:
        address: :8082

################################################################
# Traefik logs configuration
################################################################
log:
  level: INFO

#############################################################
# Access Log
#############################################################
accessLog: {}

##############################################################
# Metrics
##############################################################
metrics:
  prometheus: 
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: metrics

##############################################################
# Plugin
##############################################################
experimental:
  plugins:
    umami-plugin:
      moduleName: github.com/astappiev/traefik-umami-feeder
      version: v1.4.1

################################################################
# API and dashboard configuration
################################################################
api:
    # Disable the API in insecure mode
    insecure: false

    # Enabled Dashboard
    dashboard: true

################################################################
# Ping configuration
################################################################

serversTransport:
  insecureSkipVerify: true

################################################################
# Docker configuration backend
################################################################
providers:
    # Enable Docker configuration backend
    docker:
        exposedByDefault: false
    file:
        filename: /etc/traefik/dynamic/conf.yml

################################################################
# -- Configure your CertificateResolver here...
################################################################
certificatesResolvers:
    staging:
        acme:
            email: your-email@example.com
            storage: /etc/traefik/certs/acme.json
            caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
            #-- (Optional) Remove this section, when using DNS Challenge
            httpChallenge:
                entryPoint: web
    production:
        acme:
            email: your-email@example.com
            storage: /etc/traefik/certs/acme.json
            caServer: "https://acme-v02.api.letsencrypt.org/directory"
            #-- (Optional) Remove this section, when using DNS Challenge
            httpChallenge:
                entryPoint: web
