services:
    diun:
        image: crazymax/diun:latest
        command: serve
        hostname: server-hostname
        volumes:
            - "./data:/data"
            - "./diun.yml:/diun.yml:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            - "TZ=Europe/Paris"
            - "LOG_LEVEL=info"
            - "LOG_JSON=false"
        restart: always
