# Jellystats
# Web UI: http://jellystat:3000

services:
    jellystat-db:
        container_name: jellystat-db
        image: postgres:15.2
        environment:
            POSTGRES_DB: "jfstat"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
        volumes:
            - ./postgres-data:/var/lib/postgresql/data # Mounting the volume
        networks:
            - jfstat-network
        restart: always

    jellystat:
        container_name: jellystat
        image: cyfershepard/jellystat:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
            POSTGRES_IP: jellystat-db
            POSTGRES_PORT: 5432
            JWT_SECRET: "secret"
        volumes:
            - ./backup-data:/app/backend/backup-data # Mounting the volume
        depends_on:
            - jellystat-db
        restart: always
        networks:
            - jfstat-network
            - proxy-net
        labels:
            traefik.enable: true
            traefik.http.routers.jellystat.entrypoints: web,websecure
            traefik.http.routers.jellystat.tls: true
            traefik.http.routers.jellystat.tls.certresolver: production
            traefik.http.routers.jellystat.rule: Host(`jellystat.example.com`)
            traefik.http.services.jellystat.loadbalancer.server.port: 3000
            traefik.docker.network: proxy-network

networks:
    jfstat-network:
        driver: bridge
        ipam:
            config:
                -   subnet: 172.16.0.24/29
    proxy-net:
        name: proxy-network
        external: true