appConfig:
    backgroundImg: https://images.unsplash.com/photo-1511884642898-4c92249e20b6?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
    layout: auto
    iconSize: medium
    theme: dracula
    language: fr
    statusCheck: true
    statusCheckInterval: 20
    startingView: default
    defaultOpeningMethod: newtab
    faviconApi: allesedv
    routingMode: history
    enableMultiTasking: false
    widgetsAlwaysUseProxy: false
    webSearch:
        disableWebSearch: false
        searchEngine: google
        openingMethod: newtab
        searchBangs: {}
    enableFontAwesome: true
    enableMaterialDesignIcons: false
    hideComponents:
        hideHeading: false
        hideNav: false
        hideSearch: false
        hideSettings: true
        hideFooter: false
    auth:
        enableGuestAccess: true
        users:
            - user: gamingdy
              hash: 9ec83f470039def4b56a630b8cea95207c867dd13c5d2b867bca28a6420db502
              type: admin
        enableKeycloak: false
    showSplashScreen: false
    preventWriteToDisk: false
    preventLocalSave: false
    disableConfiguration: false
    disableConfigurationForNonAdmin: false
    allowConfigEdit: true
    enableServiceWorker: false
    disableContextMenu: false
    disableUpdateChecks: false
    disableSmartSort: false
    enableErrorReporting: false
pageInfo:
    title: Gamingdy's Home
    description: ""
    navLinks: []
    footerText: ""
    logo: https://f3.allesedv.com/64/gamingdy.fr
sections:
    - name: Monitoring
      displayData:
          sortBy: alphabetical
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
      items:
          - title: Grafana
            description: My server monitor
            icon: https://f5.allesedv.com/64/grafana.com
            url: https://monitor.gamingdy.fr
            target: newtab
            id: 0_1062_grafana
          - title: Spotify
            description: My spotify stats
            icon: https://icon.horse/icon/spotify.com
            url: https://spoti.gamingdy.fr
            target: newtab
            id: 0_529_spotify

      icon: >-
          https://is5-ssl.mzstatic.com/image/thumb/Purple115/v4/fb/5f/ce/fb5fce75-b094-175f-e17c-31f9500babc2/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/256x256bb.jpg

    - name: Social
      icon: >-
          https://b.thumbs.redditmedia.com/3nPwROTGHg8kzHLGzinIjox3Qv2VtbYOEwbJQufnp_o.png
      displayData:
          sortBy: alphabetical
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
      items:
          - title: Github
            icon: >-
                https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/2048px-Octicons-mark-github.svg.png
            url: https://github.com/gamingdy
            target: newtab
            id: 0_746_github
          - title: Me
            icon: https://f3.allesedv.com/64/gamingdy.fr
            url: https://gamingdy.fr/
            target: newtab
            id: 1_746_me

    - name: Secret
      displayData:
          sortBy: alphabetical
          rows: 1
          cols: 2
          collapsed: false
          hideForGuests: true
      items:
          - title: Torrent
            description: Torrent downloader
            icon: https://f6.allesedv.com/64/qbittorrent.org
            url: http://bit.gamingdy.fr

    - name: Tools
      displayData:
          sortBy: alphabetical
          rows: 1
          cols: 2
          collapsed: false
          hideForGuests: false
      items:
          - title: Matomo
            description: Personal analytics
            icon: https://f8.allesedv.com/64/matomo.org
            url: https://matomo.gamingdy.fr

          - title: Portainer
            description: Container manager
            icon: https://icon.horse/icon/portainer.io
            url: https://portainer.gamingdy.fr

          - title: Book reader
            description: My books reader
            icon: https://icon.horse/icon/www.kavitareader.com
            url: https://book.gamingdy.fr

          - title: Change detection
            description: Detect change on website
            icon: https://icon.horse/icon/changedetection.io
            url: http://change.gamingdy.fr/

          - title: Lynx
            description: Url shortener
            icon: https://github.com/Lynx-Shortener/Lynx/raw/main/frontend/public/logo.png
            url: https://s.gamingdy.fr/

          - title: Game server
            description: My selfhosted game server
            icon: https://icon.horse/icon/games.gamingdy.fr
            url: https://games.gamingdy.fr

          - title: Resilio Sync
            description: My resilio
            icon: https://icon.horse/icon/www.resilio.com
            url: https://sync.gamingdy.fr/

    - name: Media Server
      displayData:
          sortBy: alphabetical
          rows: 1
          cols: 2
          collapsed: false
          hideForGuests: true
      items:
          - title: Jellyseer
            description: Request manager for jellyfin
            icon: https://icon.horse/icon/mediar.gamingdy.fr
            url: https://mediar.gamingdy.fr

          - title: Jellyfin
            description: Personal media server
            icon: https://f7.allesedv.com/64/jellyfin.org
            url: https://media.gamingdy.fr

          - title: Jellystat
            description: My jellyfin stats
            icon: https://icon.horse/icon/medias.gamingdy.fr
            url: https://medias.gamingdy.fr
            id: 2_1143_jellystat

    - name: Some shit
      widgets:
          - type: clock
            label: Clock
            options:
                timeZone: Europe/Paris
                format: fr-FR
            id: 0_876_clock
          - type: joke
            label: Joke
            options:
                safeMode: true
            id: 1_876_joke
          - type: xkcd-comic
            label: Random comic
            options:
                comic: random
            id: 2_876_xkcdcomic
      items: []

pages:
    - name: Grapple
      path: "https://raw.githubusercontent.com/gamingdy/My-HomeLab/main/dashy/config/grapple.yml"
    - name: Trinity
      path: "https://raw.githubusercontent.com/gamingdy/My-HomeLab/main/dashy/config/trinity.yml"
