pageInfo:
    title: Gamingdy's Trinity
    description: ""
    navLinks: []
    footerText: ""
    logo: https://f3.allesedv.com/64/gamingdy.fr
sections:
    - name: Monitoring
      displayData:
          sortBy: alphabetical
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
      items:
          - title: Dozzle
            description: Docker logs viewer
            icon: https://icon.horse/icon/dozzle.gamingdy.fr
            url: https://dozzle.gamingdy.fr/

          - title: FileBrowser
            description: Self hosted file browser
            icon: https://f4.allesedv.com/64/filebrowser.org
            url: https://file.gamingdy.fr
          
          - title: NPM (⚠️VPN)
            description: Reverse proxy
            icon: https://icon.horse/icon/nginxproxymanager.com
            url: https://proxy.gamingdy.fr
          
          - title: VPN
            description: My VPN
            icon: https://icon.horse/icon/www.firezone.dev
            url: https://vpn.gamingdy.fr/
