services:
    seerr:
        image: ghcr.io/seerr-team/seerr:latest
        container_name: seerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Paris
        networks:
            - proxy-net
        volumes:
            - ./config:/app/config
        restart: always
        labels:
            traefik.enable: true
            traefik.http.routers.seerr.entrypoints: web,websecure
            traefik.http.routers.seerr.tls: true
            traefik.http.routers.seerr.tls.certresolver: production
            traefik.http.routers.seerr.rule: Host(`seer.example.com`)
            traefik.http.services.seerr.loadbalancer.server.port: 5055

networks:
    proxy-net:
        name: proxy-network
        external: true