---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: True

  ovh:
    class: octodns_ovh.OvhProvider
    # OVH api v6 endpoint
    endpoint: ovh-eu
    # API application key
    application_key: env/OVH_APPLICATION_KEY
    # API application secret
    application_secret: env/OVH_APPLICATION_SECRET
    # API consumer key
    consumer_key: env/OVH_CONSUMER_KEY

zones:
  gamingdy.fr.:
    sources:
      - config
    targets:
      - ovh
