# Monitoring stack
# Web UI: http://grafana:3000

version: "3"

volumes:
    prometheus-data:
        driver: local
    grafana-data:
        driver: local

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        networks:
            - monitor-network
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus-data:/prometheus
        restart: always
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=30d"

    pushgateway:
        image: prom/pushgateway
        container_name: pushgateway
        restart: always
        networks:
            - monitor-network
        ports:
            - "9091:9091"

    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        restart: always
        networks:
            - proxy-net
            - monitor-network

    cadvisor:
        image: zcube/cadvisor:latest
        container_name: cadvisor
        restart: always
        networks:
            - monitor-network
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        command:
            - "--path.rootfs=/host"
        pid: host
        restart: always
        networks:
            - monitor-network
        volumes:
            - "/:/host:ro,rslave"

networks:
    monitor-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.20/29
    proxy-net:
        name: proxy-network
        external: true
