# Jellyfin
# Web UI: http://jellyfin:8096

services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./config/:/config
            - ./data/:/data/movies
        restart: always
        networks:
            - proxy-net
        labels:
            traefik.enable: true
            traefik.http.routers.jellyfin.entrypoints: web,websecure
            traefik.http.routers.jellyfin.tls: true
            traefik.http.routers.jellyfin.tls.certresolver: production
            traefik.http.routers.jellyfin.rule: Host(`media.example.com`)
            traefik.http.services.jellyfin.loadbalancer.server.port: 8096

networks:
    proxy-net:
        name: proxy-network
        external: true