# Dozzle
# Web UI: http://dozzle:8080

services:
    dozzle:
        command: "--auth-provider simple"
        container_name: dozzle
        image: amir20/dozzle:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        networks:
            - proxy-net
        labels:
            traefik.enable: true
            traefik.http.routers.dozzle.entrypoints: web,websecure
            traefik.http.routers.dozzle.tls: true
            traefik.http.routers.dozzle.tls.certresolver: production
            traefik.http.routers.dozzle.rule: Host(`dozzle.example.com`)
            traefik.http.services.dozzle.loadbalancer.server.port: 8080

networks:
    proxy-net:
        name: proxy-network
        external: true