# Spotify Stats
# Web UI: http://spotify_client:3000

services:
    server:
        image: yooooomi/your_spotify_server
        container_name: spotify_server
        restart: always
        platform: linux/amd64
        links:
            - mongo
        depends_on:
            - mongo
        networks:
            - proxy-net
            - spoti-net
        env_file:
            - ./server.env
        labels:
            traefik.enable: true
            traefik.http.routers.spotify-server.entrypoints: web,websecure
            traefik.http.routers.spotify-server.tls: true
            traefik.http.routers.spotify-server.tls.certresolver: production
            traefik.http.routers.spotify-server.rule: Host(`api.spoti.example.com`)
            traefik.http.services.spotify-server.loadbalancer.server.port: 8080
            traefik.docker.network: proxy-network

    mongo:
        container_name: mongo
        image: mongo:4.4.8
        restart: always
        networks:
            - spoti-net
        volumes:
            - ./mongo/db:/data/db

    web:
        image: yooooomi/your_spotify_client
        container_name: spotify_client
        restart: always
        platform: linux/amd64
        networks:
            - proxy-net
        env_file:
            - ./client.env
        labels:
            traefik.enable: true
            traefik.http.routers.spotify-client.entrypoints: web,websecure
            traefik.http.routers.spotify-client.tls: true
            traefik.http.routers.spotify-client.tls.certresolver: production
            traefik.http.routers.spotify-client.rule: Host(`spoti.example.com`)
            traefik.http.services.spotify-client.loadbalancer.server.port: 3000

networks:
    spoti-net:
    proxy-net:
        name: proxy-network
        external: true