# Portainer
# Web UI: https://portainer:9443

services:
    portainer-ce:
        image: "portainer/portainer-ce:latest"
        container_name: portainer
        volumes:
            - "portainer_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock"
        restart: always
        networks:
            - proxy-net
        labels:
            traefik.enable: true
            traefik.http.routers.portainer.entrypoints: web,websecure
            traefik.http.routers.portainer.tls: true
            traefik.http.routers.portainer.tls.certresolver: production
            traefik.http.routers.portainer.rule: Host(`portainer.example.com`)
            traefik.http.services.portainer.loadbalancer.server.port: 9443
            traefik.http.services.portainer.loadbalancer.server.scheme: https

volumes:
    portainer_data:
        driver: local


networks:
    proxy-net:
        name: proxy-network
        external: true