# Portainer
# Web UI: https://portainer:9443

version: "3.9"
services:
    portainer-ce:
        image: "portainer/portainer-ce:latest"
        container_name: portainer
        volumes:
            - "portainer_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock"
        restart: always
        networks:
            - proxy-net

volumes:
    portainer_data:
        driver: local

networks:
    proxy-net:
        name: proxy-network
        external: true
