version: "3"

services:
    db:
        image: mariadb:10.11
        container_name: matomo_db
        command: --max-allowed-packet=64MB
        restart: always
        volumes:
            - db:/var/lib/mysql:Z
        environment:
            - MARIADB_AUTO_UPGRADE=1
            - MARIADB_DISABLE_UPGRADE_BACKUP=1
        env_file:
            - ./db.env
        networks:
            - matomo-network

    app:
        image: matomo
        container_name: matomo
        restart: always
        volumes:
            - ./config:/var/www/html/config:z
            - ./logs:/var/www/html/logs:z
            - matomo:/var/www/html:z
        env_file:
            - ./.env
        networks:
            - proxy-net
            - matomo-network

volumes:
    db:
    matomo:

networks:
    matomo-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.10/29
    proxy-net:
        name: proxy-network
        external: true
