# Stirling PDF Service
# Web UI: http://stirling-pdf:8080

services:
    stirling-pdf:
        container_name: stirling-pdf
        image: frooodle/s-pdf:latest
        volumes:
            #- ./trainingData:/usr/share/tessdata #Required for extra OCR languages
            - ./configs:/configs
            #- ./customFiles:/customFiles/
            #- ./logs:/logs/
        environment:
            - DOCKER_ENABLE_SECURITY=false
            - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
            - LANGS=en_GB
        networks:
            - proxy-net

networks:
    proxy-net:
        name: proxy-network
        external: true
