# Stirling PDF Service
# Web UI: http://stirling-pdf:8080

services:
    stirling-pdf:
        container_name: stirling-pdf
        image: stirlingtools/stirling-pdf:latest
        volumes:
            - ./configs:/configs
        environment:
            - DOCKER_ENABLE_SECURITY=false
            - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
            - LANGS=en_GB
        networks:
            - proxy-net
        restart: always
        labels:
            traefik.enable: true
            traefik.http.routers.pdf.entrypoints: web,websecure
            traefik.http.routers.pdf.tls: true
            traefik.http.routers.pdf.tls.certresolver: production
            traefik.http.routers.pdf.rule: Host(`pdf.example.com`)
            traefik.http.services.pdf.loadbalancer.server.port: 8080

networks:
    proxy-net:
        name: proxy-network
        external: true
