# Lynx
# Web UI: http://lynx:3000

services:
    db_lynx:
        image: mongo
        networks:
            - lynx-network
        restart: always
        env_file:
            - db.env
        volumes:
            - ./db:/data/db

    lynx:
        image: jackbailey/lynx:1
        container_name: lynx
        networks:
            - lynx-network
            - proxy-net
        restart: always
        depends_on:
            - db_lynx
        volumes:
            - ./backups:/app/backups
        env_file:
            - .env
        labels:
            traefik.enable: true
            traefik.http.routers.lynx.entrypoints: web,websecure
            traefik.http.routers.lynx.tls: true
            traefik.http.routers.lynx.tls.certresolver: production
            traefik.http.routers.lynx.rule: Host(`lynx.example.com`)
            traefik.http.services.lynx.loadbalancer.server.port: 3000
            traefik.docker.network: proxy-network

networks:
    lynx-network:
        driver: bridge
        ipam:
            config:
                -   subnet: 172.16.0.0/29
    proxy-net:
        name: proxy-network
        external: true
