# Changedetection.io
# Web UI: http://changedetection.io:5000

services:
    changedetection.io:
        image: dgtlmoon/changedetection.io
        container_name: changedetection.io
        volumes:
            - "./data:/datastore"
        networks:
            - proxy-net
        restart: always

networks:
    proxy-net:
        name: proxy-network
        external: true
