---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Found me:
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/gamingdy

    - Website:
        - abbr: GA
          icon: https://gamingdy.fr/img/favicon.png
          href: https://gamingdy.fr
