---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
hideVersion: true
target: _blank
instanceName: trinity

title: "Gamingdy's Home"
background:
  image: /images/background.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 69 # 0-100

favicon: https://gamingdy.fr/img/favicon.png

theme: dark
color: blue

useEqualHeights: true
headerStyle: boxedWidgets

layout:
  Monitoring:
    icon: /icons/monitoring.png
    tab: General
    style: row
    columns: 4

  Tools:
    icon: /icons/tools.png
    tab: General
    style: row
    columns: 4

  Media:
    icon: /icons/media.png  
    tab: General
    style: row
    columns: 4

  Grapple:
    icon: /icons/server.png
    tab: Grapple
    style: row
    columns: 4

  Trinity:
    icon: /icons/server.png
    tab: Trinity
    style: row
    columns: 4
